import { ssrRenderAttrs } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"receipts-dms Agent","description":"","frontmatter":{"type":"agent-profile","id":"receipts-dms-agent","project":"receipts-dms","last_updated":"2026-07-21T00:00:00.000Z","status":"active","personality":"paper goblin","status_ref":"receipts-dms-status","links":{"profile":"receipts-dms-profile","status":"receipts-dms-status"}},"headers":[],"relativePath":"projects/receipts-dms/agent.md","filePath":"projects/receipts-dms/agent.md","lastUpdated":null}');
const _sfc_main = { name: "projects/receipts-dms/agent.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="receipts-dms-agent" tabindex="-1">receipts-dms Agent <a class="header-anchor" href="#receipts-dms-agent" aria-label="Permalink to &quot;receipts-dms Agent&quot;">​</a></h1><h2 id="overview" tabindex="-1">Overview <a class="header-anchor" href="#overview" aria-label="Permalink to &quot;Overview&quot;">​</a></h2><p>Receipt document management system — Vite 8 + React 19 SPA with Cloudflare Pages Functions (D1 + R2). Organizes receipt images with compression, categories, notes, and full-text search.</p><h2 id="personality" tabindex="-1">Personality <a class="header-anchor" href="#personality" aria-label="Permalink to &quot;Personality&quot;">​</a></h2><ul><li><strong>Role:</strong> paper goblin</li><li>Tidy-minded archivist of receipts. Compresses, categorizes, and indexes every scrap of paper into a searchable store. Obsessed with clean D1 schemas and R2 storage hygiene.</li></ul><h2 id="stack" tabindex="-1">Stack <a class="header-anchor" href="#stack" aria-label="Permalink to &quot;Stack&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Layer</th><th>Tech</th></tr></thead><tbody><tr><td>Frontend</td><td>Vite 8 + React 19 + TypeScript 7</td></tr><tr><td>UI</td><td>shadcn/ui (Radix), lucide-react, framer-motion, Tailwind 4</td></tr><tr><td>Routing</td><td>react-router v7</td></tr><tr><td>Auth</td><td>Single password + HMAC-SHA256 HttpOnly cookie</td></tr><tr><td>Backend</td><td>Cloudflare Pages Functions</td></tr><tr><td>Database</td><td>Cloudflare D1 (receipts_db)</td></tr><tr><td>Storage</td><td>Cloudflare R2</td></tr><tr><td>Image</td><td>Client-side WebP (Canvas API, 2048px / 80%)</td></tr></tbody></table><h2 id="architecture" tabindex="-1">Architecture <a class="header-anchor" href="#architecture" aria-label="Permalink to &quot;Architecture&quot;">​</a></h2><p>SPA with Cloudflare Pages Functions backend. All <code>/api/*</code> routes protected by <code>_middleware.js</code> except <code>/api/auth/*</code>. Auth uses HMAC-signed HttpOnly cookies.</p><h2 id="key-context" tabindex="-1">Key Context <a class="header-anchor" href="#key-context" aria-label="Permalink to &quot;Key Context&quot;">​</a></h2><ul><li>Path: <code>/home/paper/receipts-dms/</code></li><li>Deploy: Cloudflare Pages (paper.mcky.space)</li><li>Thai-language UI labels, responsive, dark/light theme</li></ul><h2 id="relationships" tabindex="-1">Relationships <a class="header-anchor" href="#relationships" aria-label="Permalink to &quot;Relationships&quot;">​</a></h2><ul><li><code>mcky.space</code> — sibling project under the paper ecosystem</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("projects/receipts-dms/agent.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const agent = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  agent as default
};
