import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"สถานะ","description":"","frontmatter":{"type":"project-status","id":"receipts-dms-status","project":"receipts-dms","last_updated":"2026-07-21T00:00:00.000Z","status":"active","links":{"profile":"receipts-dms-profile","agent":"receipts-dms-agent"}},"headers":[],"relativePath":"projects/receipts-dms/status.md","filePath":"projects/receipts-dms/status.md","lastUpdated":1784695462000}');
const _sfc_main = { name: "projects/receipts-dms/status.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="สถานะ" tabindex="-1">สถานะ <a class="header-anchor" href="#สถานะ" aria-label="Permalink to &quot;สถานะ&quot;">​</a></h1><p><strong>Last deploy:</strong> 2026-07-10</p><h2 id="ฟีเจอร์" tabindex="-1">ฟีเจอร์ <a class="header-anchor" href="#ฟีเจอร์" aria-label="Permalink to &quot;ฟีเจอร์&quot;">​</a></h2><ul><li>[x] อัปโหลดพร้อมบีบอัดรูปภาพ (WebP 2048px / 80%)</li><li>[x] แถบความคืบหน้า XHR upload</li><li>[x] รายการใบเสร็จ (สลับมุมมอง table + card)</li><li>[x] รายละเอียดใบเสร็จ (preview, lightbox, แก้ไข filename/category/notes)</li><li>[x] Category CRUD (แบบ card, แก้ไขแบบยุบได้)</li><li>[x] ค้นหาแบบเต็มข้อความ (filename + notes)</li><li>[x] กรองตามหมวดหมู่</li><li>[x] การแบ่งหน้า (20 ต่อหน้า)</li><li>[x] บันทึกโน้ต (upload textarea, แสดงผล, แก้ไข)</li><li>[x] auth แบบรหัสผ่านเดียว (HMAC cookie)</li><li>[x] สลับธีม dark/light</li><li>[x] สถิติการจัดเก็บ (จำนวนใบเสร็จ + ขนาดรวม)</li><li>[x] bottom nav (มือถือ) + sidebar (เดสก์ท็อป)</li><li>[x] ป้าย UI ภาษาไทย</li><li>[x] การออกแบบ responsive</li></ul><h2 id="ที่นําออก" tabindex="-1">ที่นำออก <a class="header-anchor" href="#ที่นําออก" aria-label="Permalink to &quot;ที่นำออก&quot;">​</a></h2><ul><li>ระบบ tags (เคยเพิ่มแล้วลบออกทั้งหมด)</li><li>การแสดงนามสกุลไฟล์ (ซ่อนผ่าน <code>stripExtension</code>)</li><li>คอลัมน์ action ในมุมมอง table</li></ul><h2 id="ฐานข้อมูล" tabindex="-1">ฐานข้อมูล <a class="header-anchor" href="#ฐานข้อมูล" aria-label="Permalink to &quot;ฐานข้อมูล&quot;">​</a></h2><div class="language-sql vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">sql</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">receipts: id, </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">filename</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, category, content_type, </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">size</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, uploaded_at, notes</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">categories: id, </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, created_at</span></span></code></pre></div><h2 id="เส้นทาง" tabindex="-1">เส้นทาง <a class="header-anchor" href="#เส้นทาง" aria-label="Permalink to &quot;เส้นทาง&quot;">​</a></h2><table tabindex="0"><thead><tr><th>Path</th><th>Page</th></tr></thead><tbody><tr><td><code>/</code></td><td>Dashboard</td></tr><tr><td><code>/receipts</code></td><td>รายการใบเสร็จ</td></tr><tr><td><code>/receipts/:id</code></td><td>รายละเอียดใบเสร็จ</td></tr><tr><td><code>/upload</code></td><td>อัปโหลด</td></tr><tr><td><code>/categories</code></td><td>จัดการหมวดหมู่</td></tr><tr><td><code>/settings</code></td><td>ตั้งค่า</td></tr><tr><td><code>/login</code></td><td>เข้าสู่ระบบ (ไม่ต้อง auth)</td></tr></tbody></table><h2 id="บันทึกการเปลี่ยนแปลง" tabindex="-1">บันทึกการเปลี่ยนแปลง <a class="header-anchor" href="#บันทึกการเปลี่ยนแปลง" aria-label="Permalink to &quot;บันทึกการเปลี่ยนแปลง&quot;">​</a></h2><h3 id="_2026-07-21" tabindex="-1">2026-07-21 <a class="header-anchor" href="#_2026-07-21" aria-label="Permalink to &quot;2026-07-21&quot;">​</a></h3><ul><li>Rebuild OKF files — standardized frontmatter to new schema</li><li>Removed deprecated freshness/verified/expires/superseded_by fields</li></ul><h3 id="_2026-07-13" tabindex="-1">2026-07-13 <a class="header-anchor" href="#_2026-07-13" aria-label="Permalink to &quot;2026-07-13&quot;">​</a></h3><ul><li>Sync OKF knowledge base across all 8 projects</li><li>Updated workspace index with current project inventory</li><li>Refreshed documentation timestamps and freshness</li></ul><h3 id="_2026-07-10" tabindex="-1">2026-07-10 <a class="header-anchor" href="#_2026-07-10" aria-label="Permalink to &quot;2026-07-10&quot;">​</a></h3><ul><li>Last production deploy to paper.mcky.space</li><li>Full feature set implemented</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("projects/receipts-dms/status.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const status = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  status as default
};
