import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"OKF Setup Guide","description":"","frontmatter":{"type":"instruction","id":"okf-setup","last_updated":"2026-07-21T00:00:00.000Z"},"headers":[],"relativePath":"setup.md","filePath":"setup.md","lastUpdated":1784695462000}');
const _sfc_main = { name: "setup.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="okf-setup-guide" tabindex="-1">OKF Setup Guide <a class="header-anchor" href="#okf-setup-guide" aria-label="Permalink to &quot;OKF Setup Guide&quot;">​</a></h1><p>Quick start for agents and humans cloning this repo.</p><h2 id="what-is-this" tabindex="-1">What Is This <a class="header-anchor" href="#what-is-this" aria-label="Permalink to &quot;What Is This&quot;">​</a></h2><p>OKF (Open Knowledge Framework) is a portable knowledge base at <code>~/OKF/</code>. It stores project context as markdown files with YAML frontmatter — profiles, agents, status, and more.</p><h2 id="quick-setup" tabindex="-1">Quick Setup <a class="header-anchor" href="#quick-setup" aria-label="Permalink to &quot;Quick Setup&quot;">​</a></h2><h3 id="_1-clone-install-mcp" tabindex="-1">1. Clone &amp; Install MCP <a class="header-anchor" href="#_1-clone-install-mcp" aria-label="Permalink to &quot;1. Clone &amp; Install MCP&quot;">​</a></h3><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">git</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> clone</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> &lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">repo-ur</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">l</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">&gt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ~/OKF</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">cd</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ~/OKF/mcp-server</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> &amp;&amp; </span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">npm</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> install</span></span></code></pre></div><h3 id="_2-configure-opencode" tabindex="-1">2. Configure OpenCode <a class="header-anchor" href="#_2-configure-opencode" aria-label="Permalink to &quot;2. Configure OpenCode&quot;">​</a></h3><p>Add to <code>~/.config/opencode/opencode.jsonc</code>:</p><div class="language-jsonc vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">jsonc</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">{</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">  &quot;mcp&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">    &quot;okf&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">      &quot;type&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;local&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">,</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">      &quot;command&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: [</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;node&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&quot;/root/OKF/mcp-server/index.js&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">],</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">      &quot;enabled&quot;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">true</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">    }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span></code></pre></div><p>Restart opencode after adding.</p><h3 id="_3-verify" tabindex="-1">3. Verify <a class="header-anchor" href="#_3-verify" aria-label="Permalink to &quot;3. Verify&quot;">​</a></h3><div class="language-bash vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">bash</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Test MCP server</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">echo</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;{&quot;jsonrpc&quot;:&quot;2.0&quot;,&quot;id&quot;:1,&quot;method&quot;:&quot;initialize&quot;,&quot;params&quot;:{&quot;protocolVersion&quot;:&quot;2024-11-05&quot;,&quot;capabilities&quot;:{},&quot;clientInfo&quot;:{&quot;name&quot;:&quot;test&quot;,&quot;version&quot;:&quot;1.0.0&quot;}}}&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> |</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> node</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> ~/OKF/mcp-server/index.js</span></span></code></pre></div><h2 id="directory-layout" tabindex="-1">Directory Layout <a class="header-anchor" href="#directory-layout" aria-label="Permalink to &quot;Directory Layout&quot;">​</a></h2><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>~/OKF/</span></span>
<span class="line"><span>├── index.md                          ← Start here — project roster</span></span>
<span class="line"><span>├── projects/&lt;project&gt;/</span></span>
<span class="line"><span>│   ├── profile.md                    ← Tech stack, architecture, deps, commands, structure</span></span>
<span class="line"><span>│   ├── agent.md                      ← Agent personality, triggers, changelog</span></span>
<span class="line"><span>│   └── status.md                     ← Live status, changelog, known issues</span></span>
<span class="line"><span>├── system/</span></span>
<span class="line"><span>│   ├── conventions.md                ← Communication rules, Universal Prompt</span></span>
<span class="line"><span>│   ├── glossary.md                   ← Terminology</span></span>
<span class="line"><span>│   ├── personalities.md              ← Agent personalities</span></span>
<span class="line"><span>│   ├── sync-log.md                   ← Change history</span></span>
<span class="line"><span>│   └── TODOS.md                      ← TODOs convention</span></span>
<span class="line"><span>├── mcp-server/                       ← Local MCP server</span></span>
<span class="line"><span>│   ├── index.js</span></span>
<span class="line"><span>│   ├── lib/</span></span>
<span class="line"><span>│   │   ├── okf.js                    ← Core OKF functions</span></span>
<span class="line"><span>│   │   ├── db.js                     ← SQLite connection</span></span>
<span class="line"><span>│   │   ├── sync.js                   ← Markdown → SQLite sync</span></span>
<span class="line"><span>│   │   └── tools.js                  ← MCP tools</span></span>
<span class="line"><span>│   └── okf.db                        ← SQLite database</span></span>
<span class="line"><span>└── skills/                           ← Specialized skills</span></span></code></pre></div><h2 id="how-the-kb-works" tabindex="-1">How the KB Works <a class="header-anchor" href="#how-the-kb-works" aria-label="Permalink to &quot;How the KB Works&quot;">​</a></h2><p>Every <code>.md</code> file uses YAML frontmatter + Markdown body:</p><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">---</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">type</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">project-profile</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">id</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">truck-profile</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">project</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">truck</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">last_updated</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">2026-07-21</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">status</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">active</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">---</span></span></code></pre></div><h3 id="file-types" tabindex="-1">File Types <a class="header-anchor" href="#file-types" aria-label="Permalink to &quot;File Types&quot;">​</a></h3><table tabindex="0"><thead><tr><th>Type</th><th>File</th><th>Purpose</th></tr></thead><tbody><tr><td><code>project-profile</code></td><td>profile.md</td><td>Tech stack, architecture, dependencies, commands, structure</td></tr><tr><td><code>agent-profile</code></td><td>agent.md</td><td>Agent personality, triggers, changelog</td></tr><tr><td><code>project-status</code></td><td>status.md</td><td>Live status, changelog, known issues</td></tr></tbody></table><h2 id="using-mcp-tools" tabindex="-1">Using MCP Tools <a class="header-anchor" href="#using-mcp-tools" aria-label="Permalink to &quot;Using MCP Tools&quot;">​</a></h2><p>The MCP server exposes 8 tools for reading and querying the KB.</p><h3 id="query" tabindex="-1">Query <a class="header-anchor" href="#query" aria-label="Permalink to &quot;Query&quot;">​</a></h3><div class="language- vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang"></span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span>okf_list_projects                    → see all projects</span></span>
<span class="line"><span>okf_get_project truck                → read truck&#39;s profile + agent + status</span></span>
<span class="line"><span>okf_search &quot;Supabase&quot;                → full-text search</span></span>
<span class="line"><span>okf_query_projects framework=React   → query by technology</span></span>
<span class="line"><span>okf_dashboard                        → summary of all projects</span></span>
<span class="line"><span>okf_project_stats                    → statistics across projects</span></span>
<span class="line"><span>okf_list_dir                         → browse structure</span></span>
<span class="line"><span>okf_get_file projects/truck/profile.md → raw file content</span></span></code></pre></div><h2 id="rules" tabindex="-1">Rules <a class="header-anchor" href="#rules" aria-label="Permalink to &quot;Rules&quot;">​</a></h2><ul><li>Use MCP tools to read/write KB — don&#39;t manually edit .md files</li><li>Dates are always YYYY-MM-DD</li><li>No Chinese characters — Thai or English only</li><li>Don&#39;t push KB changes without explicit instruction</li><li>Don&#39;t commit unless asked</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("setup.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const setup = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  setup as default
};
